# docker-compose.yml
include:
  - docker/oracle/docker-compose.oracle.yml
  - docker/groundplex/docker-compose.groundplex.yml
  - docker/minio/docker-compose.s3emulator.yml
  - docker/postgres/docker-compose.postgres.yml
  - docker/sqlserver/docker-compose.sqlserver.yml
  - docker/mysql/docker-compose.mysql.yml
  - docker/db2/docker-compose.db2.yml
  - docker/salesforce/docker-compose.salesforce-mock.yml
  - docker/kafka/docker-compose.kafka.yml
  - docker/email/docker-compose.email-mock.yml

services:
  tools:
    build:
      context: src/tools
      dockerfile: ../robot.Dockerfile
    platform: linux/amd64  # Force x86_64 for ibm_db compatibility
    container_name: snaplogic-test-example-tools-container
    image: snaplogic-test-example:latest
    environment:
      # Travis CI Build Metadata - automatically set by Travis
      # These provide context about who/what/when triggered the build
      # Safe to ignore for local development
      TRAVIS_EVENT_TYPE: ${TRAVIS_EVENT_TYPE:-}
      TRAVIS_COMMIT_AUTHOR_NAME: ${TRAVIS_COMMIT_AUTHOR_NAME:-Unknown}
      TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG:-}
      TRAVIS_BUILD_WEB_URL: ${TRAVIS_BUILD_WEB_URL:-}
      TRAVIS_BUILD_NUMBER: ${TRAVIS_BUILD_NUMBER:-}
      TRAVIS_TEST_RESULT: ${TRAVIS_TEST_RESULT:-}
      TRAVIS_BUILD_ID: ${TRAVIS_BUILD_ID:-}
      TRAVIS_COMMIT_MESSAGE: ${TRAVIS_COMMIT_MESSAGE:-}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT:-}
      TRAVIS_DURATION: ${TRAVIS_DURATION:-0}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH:-}
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - ./.env:/app/.env
      - ./env_files:/app/env_files:ro  # Mount entire env_files directory
      - ./travis_scripts/setup_travis_env.sh:/app/travis_scripts/setup_travis_env.sh
      - ./.travis.yml:/app/.travis.yml
      - ./test/suite/test_data:/opt/snaplogic/test_data
      # Optional: Add mounts for common local directories (uncomment as needed)
      # - ~/Documents:/opt/host-documents:ro
      # - ~/Downloads:/opt/host-downloads:ro
      # - ~/Desktop:/opt/host-desktop:ro
    command: [ "sh", "-c", "echo 'Tools container started' && tail -f /dev/null" ]
    profiles: [ tools ]
    networks:
      - snaplogicnet

networks:
  snaplogicnet:
    driver: bridge
