services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-snaplogic}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-TEST}"
      MYSQL_USER: "${MYSQL_USER:-testuser}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-snaplogic}"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-snaplogic}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    profiles: [ dev, mysql-dev ]
    networks:
      - snaplogicnet
    command: --default-authentication-plugin=mysql_native_password

  mysql-schema-init:
    image: mysql:8.0
    container_name: mysql-schema-init
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./scripts/mysql-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/bash", "/setup.sh"]
    profiles: [ dev, mysql-dev ]
    networks:
      - snaplogicnet

volumes:
  mysql_data:

networks:
  snaplogicnet:
    driver: bridge
