services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite
    container_name: oracle-db
    ports:
      - "${ORACLE_PORT:-1521}:1521"
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD:-Oracle123}
    volumes:
      - oracle_data:/opt/oracle/oradata

    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'select 1 from dual;' | sqlplus -s system/Oracle123@localhost/FREEPDB1" ]
      interval: 10s
      timeout: 10s
      retries: 10
    profiles: [ dev, oracle-dev ]
    networks:
      - snaplogicnet

  oracle-schema-init:
    image: container-registry.oracle.com/database/free:23.7.0.0-lite
    container_name: oracle-schema-init
    depends_on:
      oracle-db:
        condition: service_healthy
    volumes:
      - ./scripts/oracle-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/bash", "/setup.sh"]
    profiles: [ dev, oracle-dev ]
    networks:
      - snaplogicnet

volumes:
  oracle_data:

networks:
  snaplogicnet:
    driver: bridge
