services:
  activemq:
    image: apache/activemq-artemis:latest  
    container_name: snaplogic-activemq
    environment:
      ARTEMIS_USER: ${ACTIVEMQ_USER:-admin}
      ARTEMIS_PASSWORD: ${ACTIVEMQ_PASSWORD:-admin}
      ANONYMOUS_LOGIN: false
      ARTEMIS_DEFAULT_ADDRESS_ROUTING_TYPE: BOTH
      ARTEMIS_DEFAULT_QUEUE_ROUTING_TYPE: ANYCAST
      ARTEMIS_AUTO_CREATE_QUEUES: true
      ARTEMIS_AUTO_CREATE_ADDRESSES: true
      # ✅ CI-friendly memory settings
      JAVA_OPTS: "-Xmx512m -Xms256m -XX:+UseContainerSupport"
      # ✅ Additional stability settings
      EXTRA_ARGS: "--http-host 0.0.0.0 --relax-jolokia"
    # ✅ Use temporary volume for CI (no bind mount issues)
    volumes:
      - activemq-temp-data:/var/lib/artemis-instance
    ports:
      - "${ACTIVEMQ_WEB_PORT:-8161}:8161"  # Web Console
      - "${ACTIVEMQ_JMS_PORT:-61617}:61616"  # JMS Port
      - "${ACTIVEMQ_STOMP_PORT:-61614}:61613"  # STOMP Port
      - "${ACTIVEMQ_AMQP_PORT:-5673}:5672"   # AMQP Port
    profiles: [ activemq, activemq-dev ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8161/console/ || exit 1" ]
      interval: 30s      # ✅ More lenient for CI
      timeout: 15s       # ✅ Longer timeout
      retries: 10        # ✅ More retries for CI
      start_period: 60s  # ✅ Longer startup grace period
    restart: unless-stopped
    # ✅ Resource limits for CI stability
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    networks:
      - snaplogicnet

  activemq-setup:
    image: curlimages/curl:latest
    container_name: snaplogic-activemq-setup
    depends_on:
      activemq:
        condition: service_healthy
    volumes:
      - ./activemq-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/sh", "/setup.sh"]
    profiles: [ activemq ]
    networks:
      - snaplogicnet
    # ✅ Make setup non-critical
    restart: "no"

# ✅ Temporary volume for CI environments
volumes:
  activemq-temp-data:
    driver: local

networks:
  snaplogicnet:
    driver: bridge
