services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver-db
    ports:
      - "${MSSQL_PORT:-1433}:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD:-Snaplogic123!}"
      MSSQL_PID: "${MSSQL_PID:-Developer}"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ../../sqlserver-init:/docker-entrypoint-initdb.d
      - ./entrypoint.sh:/entrypoint.sh:ro
    # Use custom entrypoint to disable encryption
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Snaplogic123!", "-Q", "SELECT 1", "-b", "-C"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    profiles: [ dev, sqlserver-dev ]
    networks:
      - snaplogicnet

  sqlserver-schema-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: sqlserver-schema-init
    depends_on:
      sqlserver-db:
        condition: service_healthy
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - ./sqlserver-setup.sh:/setup.sh:ro
    entrypoint: ["/bin/bash", "/setup.sh"]
    profiles: [ dev, sqlserver-dev ]
    networks:
      - snaplogicnet

volumes:
  sqlserver_data:

networks:
  snaplogicnet:
    driver: bridge
